services:
  redis:
    image: redis:7-alpine
    container_name: findbataysk_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - findbataysk_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: findbataysk_bot
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - findbataysk_network
      - supabase_default
    volumes:
      - ./bot/media:/app/bot/media

volumes:
  redis_data:
    driver: local

networks:
  findbataysk_network:
    driver: bridge
  # Подключение к сети Supabase для доступа к его PostgreSQL
  supabase_default:
    external: true
